#!/bin/bash

set -e

# The script used to execute the tool will be named with the
# ._wb_ prefix to avoid collision with any other files

# Set all of the environment variables defined by the
# parameters for the launcher
source ._wb_launcher_env

# Run the tool with the `run.sh` script defined by the
# tool developer. While running this command, route any
# messages to standard out or standard error to canonical
# filepaths
./._wb_tool_run.sh \
2> ._wb_error.txt \
1> ._wb_output.txt
