name: "CI"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Install code
        uses: actions/setup-python@v3
        run: pip3 install --user ./

      - name: Test
        run: bats tests/cli.bats